version: "3"

services:

  mariadb:
    build:
      context: ./requirements/mariadb
    ports:
      - "3306"
    env_file:
      - .env
    volumes:
      - db_files:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    ports:
      - "9000"
    volumes:
      - wp_files:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  
  redis:
    build:
      context: ./requirements/bonus/redis
    ports:
     - "6379:6379"
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - redis_cache:/data
    
  website:
    build:
      context: ./requirements/bonus/website
    restart: always
    networks:
      - inception
    ports:
      - "1212:1212"

  adminer:
    build:
      context: ./requirements/bonus/adminer
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception
  
  ftp-server:
    build:
      context: ./requirements/bonus/ftp-server
    restart: always
    env_file:
      - .env
    volumes:
      - wp_files:/home/bperriol/ftp
    networks:
      - inception
    ports:
      - "21:21"
      - "40000-40009:40000-40009"
    
  cadvisor:
    build:
      context: ./requirements/bonus/cadvisor
    restart: always
    env_file:
      - .env
    ports:
      - "8585:8585"
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  wp_files:
    driver: local
    driver_opts:
      type: none
      device: /home/bperriol/data/wordpress
      o: bind
  db_files:
    driver: local
    driver_opts:
      type: none
      device: /home/bperriol/data/db
      o: bind
  redis_cache:
    driver: local
    driver_opts:
      type: none
      device: /home/bperriol/data/redis
      o: bind

networks:
  inception:
    driver: bridge
