version: "3"

services:

  mariadb:
    #image: mariadb:10
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - 3306
    env_file:
      - .env
    volumes:
      - mariadb_files:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - 9000
    volumes:
      - wp_files:/var/www/html
    env_file:
      - .env
    networks:
      - inception

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wp_files:/var/www/html
    env_file:
      - .env
    networks:
      - inception

volumes:
  wp_files:
    driver: local
    driver_opts:
      type: none
      device: /home/bperriol/data/wordpress
      o: bind
  mariadb_files:
    driver: local
    driver_opts:
      type: none
      device: /home/bperriol/data/mariadb
      o: bind


networks:
  inception:
    driver: bridge
